param(
  [string]$RepoRoot = "C:\dev\Shoots"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Info($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Warn($msg) { Write-Host "!!  $msg" -ForegroundColor Yellow }
function Hit($msg)  { Write-Host "    $msg" -ForegroundColor Gray }

$uiProj = Join-Path $RepoRoot "ui\Shoots.Ui\Shoots.Ui.csproj"
$uiDir  = Join-Path $RepoRoot "ui\Shoots.Ui"

if (-not (Test-Path $uiProj)) { throw "Missing UI project: $uiProj" }
if (-not (Test-Path $uiDir))  { throw "Missing UI dir: $uiDir" }

# -----------------------------
# A) Ensure UI references required projects
# -----------------------------
Info "Ensuring UI project references Runtime.Ui.Abstractions + Runtime.Abstractions + Contracts..."

$uiCsproj = Get-Content -LiteralPath $uiProj -Raw

$needRefs = @(
  "..\..\src\Runtime\Shoots.Runtime.Ui.Abstractions\Shoots.Runtime.Ui.Abstractions.csproj",
  "..\..\src\Runtime\Shoots.Runtime.Abstractions\Shoots.Runtime.Abstractions.csproj",
  "..\..\src\Contracts\Shoots.Contracts.Core\Shoots.Contracts.Core.csproj"
)

foreach ($ref in $needRefs) {
  if ($uiCsproj -notmatch [regex]::Escape($ref)) {
    $insert = "  <ItemGroup>`r`n    <ProjectReference Include=`"$ref`" />`r`n  </ItemGroup>`r`n"
    $uiCsproj = $uiCsproj -replace "\r?\n</Project>\s*$", "`r`n$insert</Project>`r`n"
    Hit "added ProjectReference: $ref"
  }
}

Set-Content -LiteralPath $uiProj -Value $uiCsproj -NoNewline

# -----------------------------
# B) Add / update UI GlobalUsings.cs
# -----------------------------
Info "Ensuring UI GlobalUsings.cs exists..."

$globalUsings = Join-Path $uiDir "GlobalUsings.cs"
$globalText = @"
// Auto-generated by Fix-ShootsUiBuild2.ps1
global using Shoots.Runtime.Ui.Abstractions;
global using Shoots.Runtime.Abstractions;
global using Shoots.Contracts.Core;

global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
"@

if (-not (Test-Path $globalUsings)) {
  $globalText | Set-Content -LiteralPath $globalUsings -NoNewline
  Hit "created: $globalUsings"
} else {
  # Keep deterministic content (overwrite if different)
  $existing = Get-Content -LiteralPath $globalUsings -Raw
  if ($existing -ne $globalText) {
    $globalText | Set-Content -LiteralPath $globalUsings -NoNewline
    Hit "updated: $globalUsings"
  } else {
    Hit "already OK: $globalUsings"
  }
}

# -----------------------------
# Helpers: safe array + scanning
# -----------------------------
function Get-TypeDeclFiles {
  param(
    [Parameter(Mandatory=$true)][string]$TypeName
  )

  $rx = "(?m)^\s*(public\s+)?(sealed\s+)?(partial\s+)?(class|record|struct|enum)\s+$TypeName\b"

  $hits = Get-ChildItem -Path $uiDir -Recurse -Filter *.cs |
    Where-Object { Select-String -LiteralPath $_.FullName -Pattern $rx -Quiet } |
    Select-Object -ExpandProperty FullName

  if ($null -eq $hits) { return @() }
  return @($hits)
}

function Disable-FileByIfFalse {
  param(
    [Parameter(Mandatory=$true)][string]$Path
  )

  $txt = Get-Content -LiteralPath $Path -Raw
  if ($txt -match "^\s*#if\s+false\b") {
    Hit "already disabled: $Path"
    return
  }

  $disabled = "#if false`r`n" + $txt.TrimEnd() + "`r`n#endif`r`n"
  Set-Content -LiteralPath $Path -Value $disabled -NoNewline
  Hit "DISABLED: $Path"
}

# Removes a single type definition block by naive brace matching.
# Assumes the type is a normal C# type with a body: ... { ... }
function Remove-TypeBlockFromFile {
  param(
    [Parameter(Mandatory=$true)][string]$FilePath,
    [Parameter(Mandatory=$true)][string]$TypeName
  )

  $text = Get-Content -LiteralPath $FilePath -Raw
  $rxStart = "(?m)^\s*(public\s+)?(sealed\s+)?(partial\s+)?(class|record|struct|enum)\s+$TypeName\b.*$"

  $m = [regex]::Match($text, $rxStart)
  if (-not $m.Success) {
    return $false
  }

  $startIdx = $m.Index

  # Find the first '{' after the declaration line
  $braceOpen = $text.IndexOf("{", $m.Index)
  if ($braceOpen -lt 0) {
    # If no body brace, we can't safely remove. Bail.
    Warn "Found declaration for $TypeName but couldn't find '{' in $FilePath"
    return $false
  }

  $depth = 0
  $i = $braceOpen
  for (; $i -lt $text.Length; $i++) {
    $ch = $text[$i]
    if ($ch -eq "{") { $depth++ }
    elseif ($ch -eq "}") {
      $depth--
      if ($depth -eq 0) {
        # include closing brace
        $endIdx = $i + 1

        # Extend to consume trailing whitespace/newlines
        while ($endIdx -lt $text.Length -and ($text[$endIdx] -eq "`r" -or $text[$endIdx] -eq "`n" -or $text[$endIdx] -eq " " -or $text[$endIdx] -eq "`t")) {
          # stop if we hit a non-whitespace after at least one blank line? no, consume all contiguous whitespace
          $endIdx++
        }

        $before = $text.Substring(0, $startIdx)
        $after  = $text.Substring($endIdx)

        $newText = ($before.TrimEnd() + "`r`n`r`n" + $after.TrimStart())
        Set-Content -LiteralPath $FilePath -Value $newText -NoNewline
        Hit "REMOVED duplicate type '$TypeName' block from: $FilePath"
        return $true
      }
    }
  }

  Warn "Could not match braces removing $TypeName from $FilePath (unbalanced braces?)"
  return $false
}

# -----------------------------
# C) Resolve duplicate RootFsDescriptor safely:
#    Keep RootFsDescriptor.cs, remove RootFsDescriptor type blocks from other files.
# -----------------------------
Info "Resolving duplicate RootFsDescriptor ..."

$rootPreferred = Join-Path $uiDir "ExecutionEnvironments\RootFsDescriptor.cs"
$rootFiles = Get-TypeDeclFiles -TypeName "RootFsDescriptor"

if ($rootFiles.Count -le 1) {
  Hit "found $($rootFiles.Count) declaration(s). OK."
} else {
  Hit "found $($rootFiles.Count) declaration(s):"
  foreach ($f in $rootFiles) { Hit $f }

  foreach ($f in $rootFiles) {
    if ($f -ieq $rootPreferred) {
      Hit "keeping enabled: $f"
      continue
    }

    # Prefer surgical removal over disabling whole file
    $removed = Remove-TypeBlockFromFile -FilePath $f -TypeName "RootFsDescriptor"
    if (-not $removed) {
      Warn "Couldn't surgically remove RootFsDescriptor from $f. Disabling file as fallback."
      Disable-FileByIfFalse -Path $f
    }
  }
}

# -----------------------------
# D) Resolve duplicate ResumeMode:
#    Keep ViewModels\ResumeMode.cs, disable others (usually safe).
# -----------------------------
Info "Resolving duplicate ResumeMode ..."

$resumePreferred = Join-Path $uiDir "ViewModels\ResumeMode.cs"
$resumeFiles = Get-TypeDeclFiles -TypeName "ResumeMode"

if ($resumeFiles.Count -le 1) {
  Hit "found $($resumeFiles.Count) declaration(s). OK."
} else {
  Hit "found $($resumeFiles.Count) declaration(s):"
  foreach ($f in $resumeFiles) { Hit $f }

  foreach ($f in $resumeFiles) {
    if ($f -ieq $resumePreferred) {
      Hit "keeping enabled: $f"
      continue
    }
    Disable-FileByIfFalse -Path $f
  }
}

# -----------------------------
# E) MainWindowViewModel.cs: remove embedded file-scoped namespaces (CS8955)
# -----------------------------
Info "Fixing MainWindowViewModel.cs mixed namespace style (removing embedded file-scoped namespaces)..."

$mainVm = Join-Path $uiDir "ViewModels\MainWindowViewModel.cs"
if (Test-Path $mainVm) {
  $txt = Get-Content -LiteralPath $mainVm -Raw

  # Remove ONLY file-scoped namespace lines: "namespace Foo;"
  $new = [regex]::Replace(
    $txt,
    "(?m)^\s*namespace\s+[A-Za-z0-9_.]+\s*;\s*$\r?\n?",
    "",
    [Text.RegularExpressions.RegexOptions]::Multiline
  )

  if ($new -ne $txt) {
    Set-Content -LiteralPath $mainVm -Value $new -NoNewline
    Hit "stripped embedded file-scoped namespace lines from: $mainVm"
  } else {
    Hit "no embedded file-scoped namespace lines found in: $mainVm"
  }
} else {
  Warn "Missing file: $mainVm"
}

# -----------------------------
# F) Output next steps
# -----------------------------
Info "Done."

Hit "Now run:"
Hit "  dotnet build Shoots.sln -c Debug -v minimal"
Hit ""
Hit "If UI compiles but Loader still fails, we will patch Loader with explicit snapshot->descriptor conversions (not global search/replace carnage)."