param(
  [string]$RepoRoot = "C:\dev\Shoots"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Info($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Warn($msg) { Write-Host "!!  $msg" -ForegroundColor Yellow }
function Hit($msg)  { Write-Host "    $msg" -ForegroundColor Gray }

function Require-Path([string]$p, [string]$label) {
  if (-not (Test-Path -LiteralPath $p)) { throw ("Missing {0}: {1}" -f $label, $p) } # <- avoids "$label:" parse trap
}

$uiProj = Join-Path $RepoRoot "ui\Shoots.Ui\Shoots.Ui.csproj"
$uiDir  = Join-Path $RepoRoot "ui\Shoots.Ui"
$loaderDir = Join-Path $RepoRoot "src\Runtime\Shoots.Runtime.Loader"

Require-Path $uiProj "UI project"
Require-Path $uiDir  "UI dir"
if (Test-Path -LiteralPath $loaderDir) { Hit "Found Loader dir: $loaderDir" }

# -----------------------------
# A) Ensure UI references required projects + CommunityToolkit.Mvvm
# -----------------------------
Info "Ensuring UI references required projects + CommunityToolkit.Mvvm..."

$uiCsprojText = Get-Content -LiteralPath $uiProj -Raw

$needProjRefs = @(
  "..\..\src\Runtime\Shoots.Runtime.Ui.Abstractions\Shoots.Runtime.Ui.Abstractions.csproj",
  "..\..\src\Contracts\Shoots.Contracts.Core\Shoots.Contracts.Core.csproj"
)

foreach ($ref in $needProjRefs) {
  if ($uiCsprojText -notmatch [regex]::Escape($ref)) {
    $insert = "  <ItemGroup>`r`n    <ProjectReference Include=`"$ref`" />`r`n  </ItemGroup>`r`n"
    $uiCsprojText = $uiCsprojText -replace "\r?\n</Project>\s*$", "`r`n$insert</Project>`r`n"
    Hit "added ProjectReference: $ref"
  } else {
    Hit "already has ProjectReference: $ref"
  }
}

# Ensure CommunityToolkit.Mvvm package reference (for AsyncRelayCommand)
if ($uiCsprojText -notmatch "CommunityToolkit\.Mvvm") {
  $pkg = @"
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>
"@
  $uiCsprojText = $uiCsprojText -replace "\r?\n</Project>\s*$", "`r`n$pkg`r`n</Project>`r`n"
  Hit "added PackageReference: CommunityToolkit.Mvvm (8.3.2)"
} else {
  Hit "already has CommunityToolkit.Mvvm reference"
}

Set-Content -LiteralPath $uiProj -Value $uiCsprojText -NoNewline

# -----------------------------
# B) GlobalUsings.cs: stop ambiguous global imports; use aliases instead
# -----------------------------
Info "Rewriting UI GlobalUsings.cs to eliminate ambiguity..."

$globalUsings = Join-Path $uiDir "GlobalUsings.cs"

$globalText = @"
// Auto-generated by Fix-ShootsUiBuild3.ps1
// Purpose: remove ambiguous type collisions by using aliases instead of global namespace dumps.

global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;

// MVVM (AsyncRelayCommand, ObservableObject, etc.)
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;

// Prefer UI abstractions in UI layer
global using Shoots.Runtime.Ui.Abstractions;

// Contracts types (tool catalogs, etc.)
global using Shoots.Contracts.Core;

// ---- Ambiguity killers ----
// ToolCatalogSnapshot exists in multiple assemblies; UI should speak Contracts.
global using ToolCatalogSnapshot = Shoots.Contracts.Core.ToolCatalogSnapshot;

// RuntimeResult also collides; UI should speak UI abstractions.
global using UiRuntimeResult = Shoots.Runtime.Ui.Abstractions.RuntimeResult;

// RootFsDescriptor collides with Runtime.Abstractions; UI should use its own.
global using UiRootFsDescriptor = Shoots.UI.ExecutionEnvironments.RootFsDescriptor;
"@

$existing = if (Test-Path -LiteralPath $globalUsings) { Get-Content -LiteralPath $globalUsings -Raw } else { "" }
if ($existing -ne $globalText) {
  $globalText | Set-Content -LiteralPath $globalUsings -NoNewline
  Hit "updated: $globalUsings"
} else {
  Hit "already OK: $globalUsings"
}

# -----------------------------
# C) Patch ExecutionEnvironmentAiHelpSurface.cs RootFsDescriptor ambiguity
# -----------------------------
Info "Patching ExecutionEnvironmentAiHelpSurface.cs for RootFsDescriptor ambiguity..."

$aiHelpSurf = Join-Path $uiDir "AiHelp\ExecutionEnvironmentAiHelpSurface.cs"
if (Test-Path -LiteralPath $aiHelpSurf) {
  $t = Get-Content -LiteralPath $aiHelpSurf -Raw

  # 1) Ensure we have the alias usage line if file has usings.
  if ($t -notmatch "(?m)^\s*using\s+UiRootFsDescriptor\s*=\s*Shoots\.UI\.ExecutionEnvironments\.RootFsDescriptor\s*;") {
    # Insert after last using; if none, insert at top.
    if ($t -match "(?ms)^(using\s+[^\r\n]+;\s*)+") {
      $t = [regex]::Replace($t, "(?ms)^(using\s+[^\r\n]+;\s*)+", { param($m) $m.Value + "using UiRootFsDescriptor = Shoots.UI.ExecutionEnvironments.RootFsDescriptor;`r`n" }, 1)
    } else {
      $t = "using UiRootFsDescriptor = Shoots.UI.ExecutionEnvironments.RootFsDescriptor;`r`n" + $t
    }
    Hit "inserted alias using UiRootFsDescriptor"
  }

  # 2) Replace plain RootFsDescriptor tokens with UiRootFsDescriptor (only in this file).
  $t2 = [regex]::Replace($t, "(?<!\.)\bRootFsDescriptor\b", "UiRootFsDescriptor")
  if ($t2 -ne $t) {
    Set-Content -LiteralPath $aiHelpSurf -Value $t2 -NoNewline
    Hit "rewrote RootFsDescriptor -> UiRootFsDescriptor in: $aiHelpSurf"
  } else {
    Hit "no RootFsDescriptor tokens to rewrite in: $aiHelpSurf"
  }
} else {
  Warn "Missing: $aiHelpSurf"
}

# -----------------------------
# D) Generate compile stubs for missing UI-only types (keeps you moving)
# -----------------------------
Info "Generating UI compile stubs for missing types (ExecutionState, BlueprintEntryViewModel, ProviderCapabilityMatrixRow, ExecutionEnvironmentSettings)..."

$stubFile = Join-Path $uiDir "_UiCompileStubs.g.cs"

$stubText = @"
// <auto-generated/>
// Generated by Fix-ShootsUiBuild3.ps1
// These are minimal compile stubs to unblock WPF/UI compilation when types drift.
// Replace/upgrade with real implementations later.

#nullable enable
namespace Shoots.Ui.ViewModels
{
    // Minimal placeholder; adjust later to match real state model.
    public enum ExecutionState
    {
        Unknown = 0,
        Idle = 1,
        Running = 2,
        Waiting = 3,
        Completed = 4,
        Failed = 5
    }

    public sealed class BlueprintEntryViewModel : ObservableObject
    {
        private string _name = "";
        public string Name { get => _name; set => SetProperty(ref _name, value); }

        private string _path = "";
        public string Path { get => _path; set => SetProperty(ref _path, value); }
    }

    public sealed class ProviderCapabilityMatrixRow : ObservableObject
    {
        private string _providerId = "";
        public string ProviderId { get => _providerId; set => SetProperty(ref _providerId, value); }

        private string _capability = "";
        public string Capability { get => _capability; set => SetProperty(ref _capability, value); }

        private bool _supported;
        public bool Supported { get => _supported; set => SetProperty(ref _supported, value); }
    }
}

namespace Shoots.UI.ExecutionEnvironments
{
    // Minimal placeholder; your real model probably has more fields.
    public sealed class ExecutionEnvironmentSettings
    {
        public string Name { get; set; } = "Default";
        public RootFsDescriptor Root { get; set; } = new RootFsDescriptor();
    }
}
"@

$stubExisting = if (Test-Path -LiteralPath $stubFile) { Get-Content -LiteralPath $stubFile -Raw } else { "" }
if ($stubExisting -ne $stubText) {
  $stubText | Set-Content -LiteralPath $stubFile -NoNewline
  Hit "wrote: $stubFile"
} else {
  Hit "already OK: $stubFile"
}

# -----------------------------
# E) Patch service interface drift with compile-safe implementations
# -----------------------------
Info "Patching UI services for interface drift (compile-safe method signatures)..."

function Ensure-Methods-In-ClassFile {
  param(
    [Parameter(Mandatory=$true)][string]$FilePath,
    [Parameter(Mandatory=$true)][string]$ClassName,
    [Parameter(Mandatory=$true)][string]$MethodsBlockMarker,
    [Parameter(Mandatory=$true)][string]$MethodsBlock
  )

  if (-not (Test-Path -LiteralPath $FilePath)) { Warn "Missing: $FilePath"; return }

  $src = Get-Content -LiteralPath $FilePath -Raw
  if ($src -match [regex]::Escape($MethodsBlockMarker)) {
    Hit "already patched: $FilePath"
    return
  }

  # Insert before last closing brace in file (naive but effective for standard single-class files).
  $idx = $src.LastIndexOf("}")
  if ($idx -lt 0) { Warn "No closing brace found in $FilePath"; return }

  $new = $src.Substring(0, $idx).TrimEnd() + "`r`n`r`n" + $MethodsBlockMarker + "`r`n" + $MethodsBlock + "`r`n`r`n" + $src.Substring($idx)
  Set-Content -LiteralPath $FilePath -Value $new -NoNewline
  Hit "patched: $FilePath"
}

# ExecutionCommandService: implement expected interface members
$execSvc = Join-Path $uiDir "Services\ExecutionCommandService.cs"
$execMarker = "// ---- Fix-ShootsUiBuild3: interface drift shims ----"
$execMethods = @"
    // Compile-safe shims. Replace with real wiring once UI flow is stable.
    public Task StartAsync(Shoots.Runtime.Ui.Abstractions.BuildPlan plan, Shoots.Runtime.Ui.Abstractions.HostRunOptions? options, CancellationToken cancellationToken)
        => Task.CompletedTask;

    public Task<Shoots.Runtime.Ui.Abstractions.ExecutionStatusSnapshot> RefreshStatusAsync(CancellationToken cancellationToken)
        => Task.FromResult(new Shoots.Runtime.Ui.Abstractions.ExecutionStatusSnapshot());
"@
Ensure-Methods-In-ClassFile -FilePath $execSvc -ClassName "ExecutionCommandService" -MethodsBlockMarker $execMarker -MethodsBlock $execMethods

# HostExecutionService: implement expected interface members
$hostSvc = Join-Path $uiDir "Services\HostExecutionService.cs"
$hostMarker = "// ---- Fix-ShootsUiBuild3: interface drift shims ----"
$hostMethods = @"
    // Compile-safe shims. Replace with real wiring once host integration is ready.
    public Task ResumeAsync(
        Shoots.Runtime.Ui.Abstractions.BuildPlan plan,
        Shoots.Runtime.Ui.Abstractions.DecisionInjectionRequest request,
        Shoots.Runtime.Ui.Abstractions.HostResumeIntent intent,
        CancellationToken cancellationToken)
        => Task.CompletedTask;

    public ToolCatalogSnapshot GetToolCatalogSnapshot(Shoots.Runtime.Ui.Abstractions.BuildPlan plan)
        => new ToolCatalogSnapshot();
"@
Ensure-Methods-In-ClassFile -FilePath $hostSvc -ClassName "HostExecutionService" -MethodsBlockMarker $hostMarker -MethodsBlock $hostMethods

# -----------------------------
# F) Loader: add Snapshot->Descriptor conversion helpers used by AiHelpFacade
# -----------------------------
Info "Adding Loader conversion shim for Snapshot->Descriptor (AiHelpFacade helpers)..."

$convFile = Join-Path $loaderDir "AiHelpFacade.Conversions.g.cs"
if (Test-Path -LiteralPath $loaderDir) {
  $convText = @"
// <auto-generated/>
// Generated by Fix-ShootsUiBuild3.ps1
// Purpose: provide compile-time conversions between *Snapshot and *Descriptor types.

#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using Shoots.Runtime.Ui.Abstractions;

namespace Shoots.Runtime.Loader
{
    internal static class UiDescriptorConversions
    {
        internal static AiIntentDescriptor ToDescriptor(this AiIntentSnapshot s)
            => new AiIntentDescriptor(s.Id, s.Name);

        internal static RoleDescriptor ToDescriptor(this AiRoleSnapshot s)
            => new RoleDescriptor(s.Id, s.Name);

        internal static Shoots.Runtime.Abstractions.RuntimeVersion ToRuntimeVersion(this RuntimeVersionInfo v)
            => new Shoots.Runtime.Abstractions.RuntimeVersion(v.Major, v.Minor, v.Patch);

        internal static Shoots.Runtime.Abstractions.ToolCatalogSnapshot? ToRuntimeToolCatalogSnapshot(this Shoots.Contracts.Core.ToolCatalogSnapshot s)
            => null; // If runtime catalog snapshot is needed later, map it intentionally.

        internal static IReadOnlyList<ToolpackCapability> ToCapabilities(this IReadOnlyList<string> caps)
        {
            if (caps is null || caps.Count == 0) return Array.Empty<ToolpackCapability>();
            var list = new List<ToolpackCapability>(caps.Count);
            foreach (var c in caps)
            {
                if (Enum.TryParse<ToolpackCapability>(c, ignoreCase: true, out var v))
                    list.Add(v);
            }
            return list;
        }
    }
}
"@
  $convExisting = if (Test-Path -LiteralPath $convFile) { Get-Content -LiteralPath $convFile -Raw } else { "" }
  if ($convExisting -ne $convText) {
    $convText | Set-Content -LiteralPath $convFile -NoNewline
    Hit "wrote: $convFile"
  } else {
    Hit "already OK: $convFile"
  }
} else {
  Warn "Loader dir not found; skipping conversions shim."
}

Info "Done."
Hit "Now run:"
Hit "  dotnet build Shoots.sln -c Debug -v minimal"