<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Shoots.Host.Core/Shoots.Host.Core.csproj" />
    <ProjectReference Include="../../Runtime/Shoots.Runtime.Core/Shoots.Runtime.Core.csproj" />
    <ProjectReference Include="../../ProviderAdapters/Shoots.ProviderAdapters.Abstractions/Shoots.ProviderAdapters.Abstractions.csproj" />
    <ProjectReference Include="../../ProviderAdapters/Shoots.ProviderAdapters.Embedded/Shoots.ProviderAdapters.Embedded.csproj" />
    <ProjectReference Include="../../Runtime/Shoots.Runtime.Abstractions/Shoots.Runtime.Abstractions.csproj" />
    <ProjectReference Include="../../Contracts/Shoots.Contracts.Core/Shoots.Contracts.Core.csproj" />
  </ItemGroup>
</Project>
